// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/EditorialWealthAdvisoryLandingPage-kkg3RG/App.tsx": () => import("../components/mockups/templates/EditorialWealthAdvisoryLandingPage-kkg3RG/App.tsx")
};
